const baseOfferDatabase = [
  {
    offer_id: "bell_aliant_fibe_500_public",
    provider: "Bell Aliant",
    service_type: "internet",
    plan_name: "Fibe Internet 500",
    speed_down: "500M",
    speed_up: "500M",
    mobile_data: null,
    province: "PEI",
    region: "PEI",
    official_regular_price: 110,
    official_promo_price: 85,
    bill_saver_target_price: 60,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "manual_confirmation",
    credit_check_required: true,
    supports_phone_financing: false,
    support_level: "manual_confirmation",
    requires_manual_confirmation: true,
    is_sensitive_price: true,
    is_public_price: true,
    source_type: "official",
    source_url: "https://aliant.bell.ca/Bell_Internet/Products/Fibe-Internet-500-Aliant",
    last_checked: "",
    status: "inactive",
    recommendable: false,
    exclude_from_recommendations: true,
    recommended_for: "Fibre coverage users, remote work, 4K video, stable home internet",
    caution: "Final price and eligibility require manual confirmation."
  },
  {
    offer_id: "bell_aliant_fibe_1_5g_public",
    provider: "Bell Aliant",
    service_type: "internet",
    plan_name: "Fibe Internet 1.5G",
    speed_down: "1.5G",
    speed_up: "940M",
    mobile_data: null,
    province: "PEI",
    region: "PEI",
    official_regular_price: 120,
    official_promo_price: 95,
    bill_saver_target_price: 65,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "manual_confirmation",
    credit_check_required: true,
    supports_phone_financing: false,
    support_level: "manual_confirmation",
    requires_manual_confirmation: true,
    is_sensitive_price: true,
    is_public_price: true,
    source_type: "estimated_official",
    source_url: "https://aliant.bell.ca/Bell_Internet/Internet_access",
    last_checked: "",
    status: "inactive",
    recommendable: false,
    exclude_from_recommendations: true,
    recommended_for: "Large households, heavy remote work, 4K streaming, gaming",
    caution: "Address coverage and final price require manual confirmation."
  },
  {
    offer_id: "bell_aliant_internet_1g_1_5g_internal_59",
    provider: "Bell Aliant",
    service_type: "internet",
    plan_name: "Bell Aliant Fibre Internet",
    speed_down: "1.5G",
    speed_up: "940M",
    mobile_data: null,
    province: "PEI",
    region: "PEI",
    official_regular_price: 120,
    official_promo_price: 95,
    bill_saver_target_price: 59,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "manual_confirmation",
    credit_check_required: true,
    supports_phone_financing: false,
    support_level: "manual_confirmation",
    requires_manual_confirmation: true,
    is_sensitive_price: true,
    is_public_price: false,
    source_type: "available_offer",
    source_url: "",
    last_checked: "",
    status: "active",
    recommendable: true,
    exclude_from_recommendations: false,
    calculation_price_available: true,
    use_for_savings_calc: true,
    display_price_requires_confirmation: true,
    requires_installation_check: true,
    recommended_for: "PEI fibre coverage users, remote work, 4K video, large households, gaming, high-speed home internet",
    caution:
      "Final price, address availability, eligibility, installation, taxes, equipment fees, and credit approval must be confirmed by Bell or an authorized sales representative."
  },
  {
    offer_id: "koodo_internet_100",
    provider: "Koodo",
    service_type: "internet",
    plan_name: "Unlimited Internet 100",
    speed_down: "100 Mbps",
    speed_up: "10 Mbps",
    mobile_data: null,
    province: "PEI",
    region: "Canada",
    official_regular_price: 86,
    official_promo_price: 61,
    bill_saver_target_price: 61,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "postpaid",
    credit_check_required: true,
    supports_phone_financing: false,
    support_level: "standard",
    requires_manual_confirmation: false,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "official",
    source_url: "https://www.koodomobile.com/en/shop/subscriptions/internet",
    last_checked: "",
    status: "active",
    recommended_for: "Basic home internet, light streaming, small households",
    caution: "Speed and availability may vary by address."
  },
  {
    offer_id: "koodo_internet_300",
    provider: "Koodo",
    service_type: "internet",
    plan_name: "Unlimited Internet 300",
    speed_down: "300 Mbps",
    speed_up: "10 Mbps",
    mobile_data: null,
    province: "PEI",
    region: "Canada",
    official_regular_price: 106,
    official_promo_price: 80,
    bill_saver_target_price: 80,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "postpaid",
    credit_check_required: true,
    supports_phone_financing: false,
    support_level: "standard",
    requires_manual_confirmation: false,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "official",
    source_url: "https://www.koodomobile.com/en/shop/subscriptions/internet",
    last_checked: "",
    status: "active",
    recommended_for: "Most households, 4K video, remote work, video meetings",
    caution: "Final availability may depend on address."
  },
  {
    offer_id: "koodo_internet_gigabit",
    provider: "Koodo",
    service_type: "internet",
    plan_name: "Unlimited Internet Gigabit",
    speed_down: "940 Mbps",
    speed_up: "15 Mbps",
    mobile_data: null,
    province: "PEI",
    region: "Canada",
    official_regular_price: 116,
    official_promo_price: 89,
    bill_saver_target_price: 89,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "postpaid",
    credit_check_required: true,
    supports_phone_financing: false,
    support_level: "standard",
    requires_manual_confirmation: false,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "official",
    source_url: "https://www.koodomobile.com/en/shop/subscriptions/internet",
    last_checked: "",
    status: "active",
    recommended_for: "Larger households, 4K video, remote work, video meetings",
    caution: "Final availability may depend on address."
  },
  {
    offer_id: "purple_cow_internet_100",
    provider: "Purple Cow",
    category: "internet",
    service_type: "internet",
    serviceType: "internet",
    plan_name: "Purple Cow Internet 100 Mbps",
    service_name: { zh: "Purple Cow Internet 100 Mbps", "zh-TW": "Purple Cow Internet 100 Mbps", en: "Purple Cow Internet 100 Mbps" },
    speed_down: "100 Mbps",
    speed_up: "10 Mbps",
    speedMbps: 100,
    downloadMbps: 100,
    uploadMbps: 10,
    speedLabel: { zh: "下载 100 Mbps / 上传 10 Mbps", "zh-TW": "下載 100 Mbps / 上傳 10 Mbps", en: "100 Mbps down / 10 Mbps up" },
    dataLabel: { zh: "无 usage fees", "zh-TW": "無 usage fees", en: "No usage fees" },
    includedEquipment: { zh: "含 Wireless Router", "zh-TW": "含 Wireless Router", en: "Wireless Router included" },
    includes: ["internet"],
    mobile_data: null,
    province: "PEI",
    region: "PEI",
    official_regular_price: 60,
    official_promo_price: 60,
    bill_saver_target_price: 60,
    monthlyPrice: 60,
    frontendPriceText: { zh: "$60/月", "zh-TW": "$60/月", en: "$60/mo" },
    is_bundle: false,
    bundle_discount: null,
    billing_type: "postpaid",
    credit_check_required: "unknown",
    supports_phone_financing: false,
    support_level: "standard",
    requires_manual_confirmation: false,
    requiresManualReview: false,
    requiresInstallationCheck: true,
    installationFeeWaivedByBillSaver: true,
    standardInstallationFee: 55,
    use_for_savings_calc: true,
    useForSavingsCalc: true,
    calculation_price_available: true,
    display_price_requires_confirmation: false,
    displayPriceRequiresConfirmation: false,
    recommendable: true,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "official",
    source_url: "https://purplecowinternet.com/internet/",
    last_checked: "",
    status: "active",
    tags: {
      zh: ["100 Mbps", "Wireless Router", "No usage fees", "No Contracts", "Bill Saver 专享免安装费"],
      "zh-TW": ["100 Mbps", "Wireless Router", "No usage fees", "No Contracts", "Bill Saver 專享免安裝費"],
      en: ["100 Mbps", "Wireless Router", "No usage fees", "No Contracts", "Bill Saver exclusive installation fee waiver"]
    },
    description: {
      zh: "适合 100M 左右需求的用户，例如网页、社交媒体、视频通话、高清视频、轻度家庭使用。",
      "zh-TW": "適合 100M 左右需求的用戶，例如網頁、社交媒體、視訊通話、高清影片、輕度家庭使用。",
      en: "Suitable for users needing around 100 Mbps, such as browsing, social media, video calls, HD video, and light household use."
    },
    recommended_for: "Price-sensitive home internet users",
    caution: "Address availability and installation eligibility should be confirmed."
  },
  {
    offer_id: "purple_cow_internet_300",
    provider: "Purple Cow",
    category: "internet",
    service_type: "internet",
    serviceType: "internet",
    plan_name: "Purple Cow Internet 300 Mbps",
    service_name: { zh: "Purple Cow Internet 300 Mbps", "zh-TW": "Purple Cow Internet 300 Mbps", en: "Purple Cow Internet 300 Mbps" },
    speed_down: "300 Mbps",
    speed_up: "10 Mbps",
    speedMbps: 300,
    downloadMbps: 300,
    uploadMbps: 10,
    speedLabel: { zh: "下载 300 Mbps / 上传 10 Mbps", "zh-TW": "下載 300 Mbps / 上傳 10 Mbps", en: "300 Mbps down / 10 Mbps up" },
    dataLabel: { zh: "No usage fees", "zh-TW": "No usage fees", en: "No usage fees" },
    includedEquipment: { zh: "含 Wireless Router", "zh-TW": "含 Wireless Router", en: "Wireless Router included" },
    includes: ["internet"],
    mobile_data: null,
    province: "PEI",
    region: "PEI",
    official_regular_price: 80,
    official_promo_price: 80,
    bill_saver_target_price: 80,
    monthlyPrice: 80,
    frontendPriceText: { zh: "$80/月", "zh-TW": "$80/月", en: "$80/mo" },
    is_bundle: false,
    bundle_discount: null,
    billing_type: "postpaid",
    credit_check_required: "unknown",
    supports_phone_financing: false,
    support_level: "standard",
    requires_manual_confirmation: false,
    requiresManualReview: false,
    requiresInstallationCheck: true,
    installationFeeWaivedByBillSaver: true,
    standardInstallationFee: 55,
    use_for_savings_calc: true,
    useForSavingsCalc: true,
    calculation_price_available: true,
    display_price_requires_confirmation: false,
    displayPriceRequiresConfirmation: false,
    recommendable: true,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "official",
    source_url: "https://purplecowinternet.com/internet/",
    last_checked: "",
    status: "active",
    tags: {
      zh: ["300 Mbps", "Wireless Router", "No usage fees", "No Contracts", "Bill Saver 专享免安装费"],
      "zh-TW": ["300 Mbps", "Wireless Router", "No usage fees", "No Contracts", "Bill Saver 專享免安裝費"],
      en: ["300 Mbps", "Wireless Router", "No usage fees", "No Contracts", "Bill Saver exclusive installation fee waiver"]
    },
    description: {
      zh: "适合需要 300M 以上的用户，例如多人同时使用、4K 视频、视频会议、孩子上网课、多设备和普通游戏。",
      "zh-TW": "適合需要 300M 以上的用戶，例如多人同時使用、4K 影片、視訊會議、孩子線上課、多設備和普通遊戲。",
      en: "Suitable for users needing 300 Mbps or more, including multiple users, 4K video, video calls, online learning, multiple devices, and casual gaming."
    },
    recommended_for: "Standard households needing more speed for streaming, meetings, and multiple devices",
    caution: "Address availability and installation eligibility should be confirmed."
  },
  {
    offer_id: "purple_cow_internet_gig",
    provider: "Purple Cow",
    category: "internet",
    service_type: "internet",
    serviceType: "internet",
    plan_name: "Purple Cow Gig Internet",
    service_name: { zh: "Purple Cow Gig Internet", "zh-TW": "Purple Cow Gig Internet", en: "Purple Cow Gig Internet" },
    speed_down: "1 Gig",
    speed_up: "15 Mbps",
    speedMbps: 1000,
    downloadMbps: 1000,
    uploadMbps: 15,
    speedLabel: { zh: "下载 1 Gig / 上传 15 Mbps", "zh-TW": "下載 1 Gig / 上傳 15 Mbps", en: "1 Gig down / 15 Mbps up" },
    dataLabel: { zh: "No usage fees", "zh-TW": "No usage fees", en: "No usage fees" },
    includedEquipment: { zh: "含 Wireless Router", "zh-TW": "含 Wireless Router", en: "Wireless Router included" },
    includes: ["internet"],
    mobile_data: null,
    province: "PEI",
    region: "PEI",
    official_regular_price: 99,
    official_promo_price: 99,
    bill_saver_target_price: 99,
    monthlyPrice: 99,
    frontendPriceText: { zh: "$99/月", "zh-TW": "$99/月", en: "$99/mo" },
    is_bundle: false,
    bundle_discount: null,
    billing_type: "postpaid",
    credit_check_required: "unknown",
    supports_phone_financing: false,
    support_level: "standard",
    requires_manual_confirmation: false,
    requiresManualReview: false,
    requiresInstallationCheck: true,
    installationFeeWaivedByBillSaver: true,
    standardInstallationFee: 55,
    use_for_savings_calc: true,
    useForSavingsCalc: true,
    calculation_price_available: true,
    display_price_requires_confirmation: false,
    displayPriceRequiresConfirmation: false,
    recommendable: true,
    notDefaultPrimary: true,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "official",
    source_url: "https://purplecowinternet.com/internet/",
    last_checked: "",
    status: "active",
    tags: {
      zh: ["1 Gig", "Wireless Router", "No usage fees", "No Contracts", "Bill Saver 专享免安装费"],
      "zh-TW": ["1 Gig", "Wireless Router", "No usage fees", "No Contracts", "Bill Saver 專享免安裝費"],
      en: ["1 Gig", "Wireless Router", "No usage fees", "No Contracts", "Bill Saver exclusive installation fee waiver"]
    },
    description: {
      zh: "适合明确需要千兆、非常重度使用或更看重无合约和本地服务的用户。由于价格竞争力一般，不作为默认主推。",
      "zh-TW": "適合明確需要千兆、非常重度使用或更看重無合約和本地服務的用戶。由於價格競爭力一般，不作為預設主推。",
      en: "Suitable for users who specifically need gigabit service or prioritize no-contract local service. Not the default main recommendation due to weaker price competitiveness."
    },
    recommended_for: "Heavy households needing the fastest available Purple Cow internet direction",
    caution: "Address availability and installation eligibility should be confirmed."
  },
  {
    offer_id: "purple_cow_tv_manual_confirmation",
    provider: "Purple Cow",
    service_type: "tv",
    plan_name: "Purple Cow TV",
    province: "PEI",
    region: "PEI",
    official_regular_price: null,
    official_promo_price: null,
    bill_saver_target_price: null,
    billing_type: "manual_confirmation",
    support_level: "manual_confirmation",
    requires_manual_confirmation: true,
    display_price_requires_confirmation: true,
    is_sensitive_price: true,
    is_public_price: false,
    source_type: "available_offer",
    source_url: "https://purplecowinternet.com/",
    last_checked: "",
    status: "active",
    recommended_for: "Households interested in adding Purple Cow TV",
    caution: "Channel packages, device requirements, price, and availability require manual confirmation."
  },
  {
    offer_id: "eastlink_internet_350",
    provider: "Eastlink",
    category: "internet",
    service_type: "internet",
    serviceType: "internet",
    plan_name: "Eastlink Internet 350",
    service_name: { zh: "Eastlink Internet 350", "zh-TW": "Eastlink Internet 350", en: "Eastlink Internet 350" },
    speed_down: "350 Mbps",
    speed_up: "10 Mbps",
    speedMbps: 350,
    downloadMbps: 350,
    uploadMbps: 10,
    speedLabel: { zh: "下载最高 350 Mbps / 上传 10 Mbps", "zh-TW": "下載最高 350 Mbps / 上傳 10 Mbps", en: "Up to 350 Mbps down / 10 Mbps up" },
    dataLabel: { zh: "不限流量", "zh-TW": "不限流量", en: "Unlimited data" },
    unlimited_data: true,
    mobile_data: null,
    province: "PEI",
    region: "PEI",
    official_regular_price: 85,
    official_promo_price: 85,
    bill_saver_target_price: 85,
    monthlyPrice: 85,
    frontendPriceText: { zh: "$85/月", "zh-TW": "$85/月", en: "$85/mo" },
    is_bundle: false,
    bundle_discount: null,
    billing_type: "postpaid",
    credit_check_required: "unknown",
    supports_phone_financing: false,
    support_level: "standard",
    requires_manual_confirmation: false,
    requiresInstallationCheck: true,
    use_for_savings_calc: true,
    useForSavingsCalc: true,
    calculation_price_available: true,
    display_price_requires_confirmation: false,
    displayPriceRequiresConfirmation: false,
    recommendable: true,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "official",
    source_url: "https://www.eastlink.ca/internet",
    last_checked: "",
    status: "active",
    tags: {
      zh: ["350 Mbps", "不限流量", "本地运营商", "安装资格需确认"],
      "zh-TW": ["350 Mbps", "不限流量", "本地電信商", "安裝資格需確認"],
      en: ["350 Mbps", "Unlimited data", "Local provider", "Installation eligibility required"]
    },
    description: {
      zh: "适合普通家庭、4K 视频、视频会议、孩子上网课、多设备同时使用和普通游戏。价格、安装资格和可用性需按地址确认。",
      "zh-TW": "適合一般家庭、4K 影片、視訊會議、孩子線上課、多設備同時使用和普通遊戲。價格、安裝資格和可用性需按地址確認。",
      en: "Suitable for standard households, 4K video, video calls, online learning, multiple devices, and casual gaming. Price, installation eligibility, and availability should be confirmed by address."
    },
    recommended_for: "Standard households and cable internet areas",
    caution: "Price, installation eligibility, and availability should be confirmed by address."
  },
  {
    offer_id: "eastlink_gig_internet",
    provider: "Eastlink",
    category: "internet",
    service_type: "internet",
    serviceType: "internet",
    plan_name: "Eastlink Gig Internet",
    service_name: { zh: "Eastlink Gig Internet", "zh-TW": "Eastlink Gig Internet", en: "Eastlink Gig Internet" },
    speed_down: "940 Mbps",
    speed_up: "15 Mbps",
    speedMbps: 940,
    downloadMbps: 940,
    uploadMbps: 15,
    speedLabel: { zh: "下载最高 940 Mbps / 上传 15 Mbps", "zh-TW": "下載最高 940 Mbps / 上傳 15 Mbps", en: "Up to 940 Mbps down / 15 Mbps up" },
    dataLabel: { zh: "不限流量", "zh-TW": "不限流量", en: "Unlimited data" },
    unlimited_data: true,
    mobile_data: null,
    province: "PEI",
    region: "PEI",
    official_regular_price: 90,
    official_promo_price: 90,
    bill_saver_target_price: 90,
    monthlyPrice: 90,
    frontendPriceText: { zh: "$90/月", "zh-TW": "$90/月", en: "$90/mo" },
    is_bundle: false,
    bundle_discount: null,
    billing_type: "postpaid",
    credit_check_required: "unknown",
    supports_phone_financing: false,
    support_level: "standard",
    requires_manual_confirmation: false,
    requiresInstallationCheck: true,
    use_for_savings_calc: true,
    useForSavingsCalc: true,
    calculation_price_available: true,
    display_price_requires_confirmation: false,
    displayPriceRequiresConfirmation: false,
    recommendable: true,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "official",
    source_url: "https://www.eastlink.ca/internet",
    last_checked: "",
    status: "active",
    tags: {
      zh: ["Gig Internet", "不限流量", "本地运营商", "安装资格需确认"],
      "zh-TW": ["Gig Internet", "不限流量", "本地電信商", "安裝資格需確認"],
      en: ["Gig Internet", "Unlimited data", "Local provider", "Installation eligibility required"]
    },
    description: {
      zh: "适合重度家庭、多设备、高清视频、下载和远程办公。价格、安装资格和可用性需按地址确认。",
      "zh-TW": "適合重度家庭、多設備、高清影片、下載和遠端辦公。價格、安裝資格和可用性需按地址確認。",
      en: "Suitable for heavy households, multiple devices, HD streaming, downloads, and remote work. Price, installation eligibility, and availability should be confirmed by address."
    },
    recommended_for: "Heavy households and cable internet areas",
    caution: "Price, installation eligibility, and availability should be confirmed by address."
  },
  {
    offer_id: "xplore_rural_internet",
    provider: "Xplore",
    service_type: "internet",
    plan_name: "Rural Internet",
    speed_down: "100M",
    speed_up: null,
    mobile_data: null,
    province: "PEI",
    region: "Rural PEI",
    official_regular_price: 90,
    official_promo_price: 70,
    bill_saver_target_price: 70,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "postpaid",
    credit_check_required: "unknown",
    supports_phone_financing: false,
    support_level: "standard",
    requires_manual_confirmation: true,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "estimated_public",
    source_url: "https://www.xplore.ca/",
    last_checked: "",
    status: "needs_verification",
    recommended_for: "Rural addresses without fibre or cable options",
    caution: "Speed and latency may vary by location."
  },
  {
    offer_id: "starlink_residential",
    provider: "Starlink",
    service_type: "internet",
    plan_name: "Residential",
    speed_down: null,
    speed_up: null,
    mobile_data: null,
    province: "PEI",
    region: "Rural PEI",
    official_regular_price: 140,
    official_promo_price: 140,
    bill_saver_target_price: 120,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "subscription",
    credit_check_required: false,
    supports_phone_financing: false,
    support_level: "self_serve",
    requires_manual_confirmation: false,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "estimated_public",
    source_url: "https://www.starlink.com/residential",
    last_checked: "",
    status: "needs_verification",
    recommended_for: "Rural or remote users without better wired options",
    caution: "Usually not the cheapest option; hardware and service availability should be confirmed."
  },
  {
    offer_id: "public_mobile_25gb",
    provider: "Public Mobile",
    service_type: "mobile",
    plan_name: "Public Mobile 25GB Canada-US-Mexico Subscription",
    speed_down: null,
    speed_up: null,
    network_generation: "5G",
    speed_note: "5G speed up to 250 Mbps",
    mobile_data: "25GB",
    coverage: "Canada-US-Mexico",
    province: "Canada",
    region: "Canada",
    official_regular_price: 35,
    official_promo_price: 35,
    bill_saver_target_price: 35,
    is_bundle: false,
    bundle_discount: null,
    plan_type: "prepaid_subscription",
    billing_type: "subscription",
    credit_check_required: false,
    supports_phone_financing: false,
    support_level: "self_serve",
    requires_manual_confirmation: false,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "official",
    source_url: "https://www.publicmobile.ca/en/plans",
    last_checked: "2026-06-05",
    status: "active",
    tags: ["预付卡订阅", "不需要信用核查", "Canada-US-Mexico", "1000 分钟国际长途"],
    recommended_for: "BYOD users, light to moderate data users",
    caution: "Self-serve support model."
  },
  {
    offer_id: "public_mobile_100gb",
    provider: "Public Mobile",
    service_type: "mobile",
    plan_name: "Public Mobile 100GB Canada-US-Mexico Subscription",
    speed_down: null,
    speed_up: null,
    network_generation: "5G",
    speed_note: "5G speed up to 250 Mbps",
    mobile_data: "100GB",
    coverage: "Canada-US-Mexico",
    province: "Canada",
    region: "Canada",
    official_regular_price: 40,
    official_promo_price: 40,
    bill_saver_target_price: 40,
    is_bundle: false,
    bundle_discount: null,
    plan_type: "prepaid_subscription",
    billing_type: "subscription",
    credit_check_required: false,
    supports_phone_financing: false,
    support_level: "self_serve",
    requires_manual_confirmation: false,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "official",
    source_url: "https://www.publicmobile.ca/en/plans",
    last_checked: "2026-06-05",
    status: "active",
    tags: ["预付卡订阅", "不需要信用核查", "Canada-US-Mexico", "1000 分钟国际长途"],
    recommended_for: "BYOD users, heavy data users, Canada-US-Mexico use",
    caution: "Self-serve support model."
  },
  {
    offer_id: "public_mobile_100gb_45",
    provider: "Public Mobile",
    service_type: "mobile",
    plan_name: "Public Mobile 100GB Canada-US-Mexico Subscription",
    speed_down: null,
    speed_up: null,
    network_generation: "5G",
    speed_note: "5G speed up to 250 Mbps",
    mobile_data: "100GB",
    coverage: "Canada-US-Mexico",
    province: "Canada",
    region: "Canada",
    official_regular_price: 45,
    official_promo_price: 45,
    bill_saver_target_price: 45,
    is_bundle: false,
    bundle_discount: null,
    plan_type: "prepaid_subscription",
    billing_type: "subscription",
    credit_check_required: false,
    supports_phone_financing: false,
    support_level: "self_serve",
    requires_manual_confirmation: false,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "official",
    source_url: "https://www.publicmobile.ca/en/plans",
    last_checked: "2026-06-05",
    status: "active",
    tags: ["预付卡订阅", "不需要信用核查", "Canada-US-Mexico", "1000 分钟国际长途"],
    recommended_for: "BYOD users, heavy data users, Canada-US-Mexico use",
    caution: "Self-serve support model."
  },
  {
    offer_id: "public_mobile_175gb",
    provider: "Public Mobile",
    service_type: "mobile",
    plan_name: "Public Mobile 175GB Canada-US-Mexico Subscription",
    speed_down: null,
    speed_up: null,
    network_generation: "5G",
    speed_note: "5G speed up to 250 Mbps",
    mobile_data: "175GB",
    coverage: "Canada-US-Mexico",
    province: "Canada",
    region: "Canada",
    official_regular_price: 50,
    official_promo_price: 50,
    bill_saver_target_price: 50,
    is_bundle: false,
    bundle_discount: null,
    plan_type: "prepaid_subscription",
    billing_type: "subscription",
    credit_check_required: false,
    supports_phone_financing: false,
    support_level: "self_serve",
    requires_manual_confirmation: false,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "official",
    source_url: "https://www.publicmobile.ca/en/plans",
    last_checked: "2026-06-05",
    status: "active",
    tags: ["预付卡订阅", "不需要信用核查", "Canada-US-Mexico", "1000 分钟国际长途"],
    recommended_for: "Very heavy data users",
    caution: "Self-serve support model."
  },
  {
    offer_id: "koodo_prepaid_talk_text",
    provider: "Koodo",
    service_type: "mobile",
    plan_name: "Koodo Prepaid 4G Talk & Text",
    speed_down: null,
    speed_up: null,
    mobile_data: "0GB",
    province: "Canada",
    region: "Canada",
    official_regular_price: 19,
    official_promo_price: 19,
    bill_saver_target_price: 19,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "prepaid",
    credit_check_required: false,
    supports_phone_financing: false,
    support_level: "self_serve",
    requires_manual_confirmation: false,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "official",
    source_url: "https://www.koodomobile.com/en/prepaid-plans",
    last_checked: "",
    status: "active",
    recommended_for: "Users who mainly need Canada talk and text with no or very little data",
    caution: "Prepaid/self-serve style plan. Data may require add-ons or a different prepaid plan."
  },
  {
    offer_id: "koodo_prepaid_4g_5gb",
    provider: "Koodo",
    service_type: "mobile",
    plan_name: "Koodo Prepaid 4G Light Data",
    speed_down: null,
    speed_up: null,
    mobile_data: "5GB",
    province: "Canada",
    region: "Canada",
    official_regular_price: 25,
    official_promo_price: 25,
    bill_saver_target_price: 25,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "prepaid",
    credit_check_required: false,
    supports_phone_financing: false,
    support_level: "self_serve",
    requires_manual_confirmation: false,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "estimated_official",
    source_url: "https://www.koodomobile.com/en/prepaid-plans",
    last_checked: "",
    status: "needs_verification",
    recommended_for: "Light data users who want prepaid 4G and no credit check",
    caution: "Verify current prepaid data amount and promo details before quoting."
  },
  {
    offer_id: "koodo_prepaid_4g_20gb",
    provider: "Koodo",
    service_type: "mobile",
    plan_name: "Koodo Prepaid 4G Medium Data",
    speed_down: null,
    speed_up: null,
    mobile_data: "20GB",
    province: "Canada",
    region: "Canada",
    official_regular_price: 35,
    official_promo_price: 35,
    bill_saver_target_price: 35,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "prepaid",
    credit_check_required: false,
    supports_phone_financing: false,
    support_level: "self_serve",
    requires_manual_confirmation: false,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "estimated_official",
    source_url: "https://www.koodomobile.com/en/prepaid-plans",
    last_checked: "",
    status: "needs_verification",
    recommended_for: "Light to moderate users who want prepaid 4G and no credit check",
    caution: "Verify current prepaid data amount and promo details before quoting."
  },
  {
    offer_id: "koodo_mobile_5g_60gb",
    provider: "Koodo",
    service_type: "mobile",
    plan_name: "Koodo 5G 60GB",
    speed_down: null,
    speed_up: null,
    network_generation: "5G",
    speed_note: "5G speed up to 1Gbps / 250Mbps depending on official plan terms",
    mobile_data: "60GB",
    province: "Canada",
    region: "Canada",
    official_regular_price: 45,
    official_promo_price: 45,
    bill_saver_target_price: 45,
    is_bundle: false,
    bundle_discount: null,
    plan_type: "postpaid",
    billing_type: "postpaid",
    credit_check_required: true,
    supports_phone_financing: true,
    support_level: "standard",
    requires_manual_confirmation: true,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "estimated_public",
    source_url: "https://www.koodomobile.com/en/rate-plans",
    last_checked: "2026-06-05",
    status: "needs_verification",
    tags: ["5G 60GB", "免费 Perk", "需要信用核查"],
    recommended_for: "Users who want stronger support than Public Mobile",
    caution: "Promo and activation conditions may vary."
  },
  {
    offer_id: "koodo_mobile_canada_us_mexico_60gb",
    provider: "Koodo",
    service_type: "mobile",
    plan_name: "Koodo Canada-US-Mexico 60GB",
    speed_down: null,
    speed_up: null,
    network_generation: "5G",
    speed_note: "5G speed depends on official plan terms",
    mobile_data: "60GB",
    coverage: "Canada-US-Mexico",
    province: "Canada",
    region: "Canada",
    official_regular_price: 50,
    official_promo_price: 50,
    bill_saver_target_price: 50,
    is_bundle: false,
    bundle_discount: null,
    plan_type: "postpaid",
    billing_type: "postpaid",
    credit_check_required: true,
    supports_phone_financing: true,
    support_level: "standard",
    requires_manual_confirmation: true,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "estimated_public",
    source_url: "https://www.koodomobile.com/en/rate-plans",
    last_checked: "2026-06-05",
    status: "needs_verification",
    tags: ["Canada-US-Mexico", "5G 60GB", "免费 Perk", "需要信用核查"],
    recommended_for: "Users who need Canada-US-Mexico usage",
    caution: "Promo, roaming, activation, and eligibility conditions may vary."
  },
  {
    offer_id: "koodo_mobile_5g_100gb",
    provider: "Koodo",
    service_type: "mobile",
    plan_name: "Koodo 100GB",
    speed_down: null,
    speed_up: null,
    network_generation: "5G",
    speed_note: "5G speed depends on official plan terms",
    mobile_data: "100GB",
    province: "Canada",
    region: "Canada",
    official_regular_price: 55,
    official_promo_price: 55,
    bill_saver_target_price: 55,
    is_bundle: false,
    bundle_discount: null,
    plan_type: "postpaid",
    billing_type: "postpaid",
    credit_check_required: true,
    supports_phone_financing: true,
    support_level: "standard",
    requires_manual_confirmation: true,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "estimated_public",
    source_url: "https://www.koodomobile.com/en/rate-plans",
    last_checked: "2026-06-05",
    status: "needs_verification",
    tags: ["5G 100GB", "免费 Perk", "需要信用核查"],
    recommended_for: "Users who need more postpaid mobile data",
    caution: "Promo and activation conditions may vary."
  },
  {
    offer_id: "telus_mobile_byod_100gb",
    provider: "TELUS",
    service_type: "mobile",
    plan_name: "TELUS 5G+ Complete 100GB",
    display_name: "TELUS BYOD 100GB",
    speed_down: null,
    speed_up: null,
    network_generation: "5G+",
    speed_note: "Speeds up to 2Gbps",
    mobile_data: "100GB",
    province: "Canada",
    region: "Canada",
    official_regular_price: 65,
    official_promo_price: 65,
    bill_saver_target_price: 65,
    is_bundle: false,
    bundle_discount: null,
    plan_type: "postpaid",
    billing_type: "postpaid",
    credit_check_required: true,
    supports_phone_financing: true,
    roaming_scope: "Canada/US",
    unlimited_talk_text_canada: true,
    family_discount_eligible: true,
    rate_plan_price_lock_years: 5,
    tags: ["大网覆盖", "5G+ 高速", "5 年价格锁定", "适合高流量用户", "需要信用核查"],
    support_level: "premium",
    requires_manual_confirmation: true,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "public",
    source_url: "https://www.telus.com/en/mobility/plans",
    last_checked: "2026-06-05",
    status: "needs_verification",
    recommended_for: "Users needing premium network support or higher data",
    caution: "Final price and eligibility require confirmation."
  },
  {
    offer_id: "telus_mobile_byod_unlimited",
    provider: "TELUS",
    service_type: "mobile",
    plan_name: "TELUS 5G+ Complete - Unlimited",
    display_name: "TELUS BYOD Unlimited",
    speed_down: null,
    speed_up: null,
    network_generation: "5G+",
    speed_note: "Speeds up to 2Gbps",
    mobile_data: "Unlimited",
    province: "Canada",
    region: "Canada",
    official_regular_price: 80,
    official_promo_price: 80,
    bill_saver_target_price: 80,
    is_bundle: false,
    bundle_discount: null,
    plan_type: "postpaid",
    billing_type: "postpaid",
    credit_check_required: true,
    supports_phone_financing: true,
    roaming_scope: "Canada/US/Mexico",
    unlimited_talk_text_canada: true,
    family_discount_eligible: true,
    rate_plan_price_lock_years: 5,
    tags: ["大网覆盖", "5G+ 高速", "5 年价格锁定", "无限高速数据", "需要信用核查"],
    support_level: "premium",
    requires_manual_confirmation: true,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "public",
    source_url: "https://www.telus.com/en/mobility/plans",
    last_checked: "2026-06-05",
    status: "needs_verification",
    recommended_for: "Heavy data users who want a premium postpaid plan",
    caution: "Final price, included roaming benefits, and eligibility require confirmation."
  },
  {
    offer_id: "telus_mobile_byod_unlimited_explore",
    provider: "TELUS",
    service_type: "mobile",
    plan_name: "TELUS 5G+ Complete - Unlimited Explore",
    display_name: "TELUS BYOD Unlimited Explore",
    speed_down: null,
    speed_up: null,
    network_generation: "5G+",
    speed_note: "Speeds up to 2Gbps",
    mobile_data: "Unlimited",
    province: "Canada",
    region: "Canada",
    official_regular_price: 95,
    official_promo_price: 95,
    bill_saver_target_price: 95,
    is_bundle: false,
    bundle_discount: null,
    plan_type: "postpaid",
    billing_type: "postpaid",
    credit_check_required: true,
    supports_phone_financing: true,
    roaming_scope: "International Explore destinations",
    unlimited_talk_text_canada: true,
    family_discount_eligible: true,
    rate_plan_price_lock_years: 5,
    tags: ["大网覆盖", "5G+ 高速", "5 年价格锁定", "国际旅行适合", "需要信用核查"],
    support_level: "premium",
    requires_manual_confirmation: true,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "public",
    source_url: "https://www.telus.com/en/mobility/plans",
    last_checked: "2026-06-05",
    status: "needs_verification",
    recommended_for: "Frequent travellers who need broader international plan benefits",
    caution: "Final price, included destinations, roaming benefits, and eligibility require confirmation."
  },
  {
    offer_id: "bell_mobile_byod_100gb_public",
    provider: "Bell",
    service_type: "mobile",
    plan_name: "Bell BYOD 100GB",
    speed_down: null,
    speed_up: null,
    mobile_data: "100GB",
    province: "Canada",
    region: "Canada",
    official_regular_price: 65,
    official_promo_price: 55,
    bill_saver_target_price: 45,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "postpaid",
    credit_check_required: true,
    supports_phone_financing: true,
    support_level: "premium",
    requires_manual_confirmation: true,
    is_sensitive_price: true,
    is_public_price: true,
    source_type: "estimated_public",
    source_url: "https://www.bell.ca/Mobility/Cell_phone_plans",
    last_checked: "",
    status: "inactive",
    recommendable: false,
    exclude_from_recommendations: true,
    recommended_for: "Users needing Bell network or bundle possibilities",
    caution: "Do not display sensitive price; final price requires manual confirmation."
  },
  {
    offer_id: "virgin_plus_byod_60gb",
    provider: "Virgin Plus",
    service_type: "mobile",
    plan_name: "Virgin Plus BYOD 60GB",
    speed_down: null,
    speed_up: null,
    mobile_data: "60GB",
    province: "Canada",
    region: "Canada",
    official_regular_price: 50,
    official_promo_price: 45,
    bill_saver_target_price: 40,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "postpaid",
    credit_check_required: true,
    supports_phone_financing: true,
    support_level: "standard",
    requires_manual_confirmation: true,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "estimated_public",
    source_url: "https://www.virginplus.ca/en/plans/postpaid.html",
    last_checked: "",
    status: "needs_verification",
    recommended_for: "BYOD users comparing flanker brands",
    caution: "Promo eligibility may vary."
  },
  {
    offer_id: "rogers_mobile_byod_100gb",
    provider: "Rogers",
    service_type: "mobile",
    plan_name: "Rogers BYOD 100GB",
    speed_down: null,
    speed_up: null,
    mobile_data: "100GB",
    province: "Canada",
    region: "Canada",
    official_regular_price: 65,
    official_promo_price: 55,
    bill_saver_target_price: 45,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "postpaid",
    credit_check_required: true,
    supports_phone_financing: true,
    support_level: "premium",
    requires_manual_confirmation: true,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "estimated_public",
    source_url: "https://www.rogers.com/plans",
    last_checked: "",
    status: "needs_verification",
    recommended_for: "Users comparing major carrier plans",
    caution: "Final price and activation conditions may vary."
  },
  {
    offer_id: "fido_mobile_byod_50gb",
    provider: "Fido",
    service_type: "mobile",
    plan_name: "Fido BYOD 50GB",
    speed_down: null,
    speed_up: null,
    mobile_data: "50GB",
    province: "Canada",
    region: "Canada",
    official_regular_price: 50,
    official_promo_price: 45,
    bill_saver_target_price: 35,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "postpaid",
    credit_check_required: true,
    supports_phone_financing: true,
    support_level: "standard",
    requires_manual_confirmation: true,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "estimated_public",
    source_url: "https://www.fido.ca/plans",
    last_checked: "",
    status: "needs_verification",
    recommended_for: "BYOD users comparing flanker brands",
    caution: "Promo eligibility may vary."
  },
  {
    offer_id: "bell_mobile_talk_text_internal_25",
    provider: "Bell",
    service_type: "mobile",
    plan_name: "Bell Talk & Text Canada",
    speed_down: null,
    speed_up: null,
    mobile_data: "0GB",
    province: "Canada",
    region: "Canada",
    official_regular_price: null,
    official_promo_price: null,
    bill_saver_target_price: 25,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "internal_channel",
    credit_check_required: true,
    supports_phone_financing: "unknown",
    support_level: "manual_confirmation",
    requires_manual_confirmation: true,
    is_sensitive_price: true,
    is_public_price: false,
    source_type: "internal_channel",
    source_url: "",
    last_checked: "",
    status: "inactive",
    recommendable: false,
    exclude_from_recommendations: true,
    use_for_savings_calc: false,
    recommended_for: "Users who need no data, Canada-wide talk and text only",
    caution: "Requires manual confirmation. Intended with pre-authorized debit setup."
  },
  {
    offer_id: "bell_mobile_100gb_internal_40",
    provider: "Bell",
    service_type: "mobile",
    plan_name: "Bell 100GB Canada",
    speed_down: null,
    speed_up: null,
    mobile_data: "100GB",
    province: "Canada",
    region: "Canada",
    official_regular_price: null,
    official_promo_price: null,
    bill_saver_target_price: 40,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "manual_confirmation",
    credit_check_required: true,
    supports_phone_financing: "unknown",
    support_level: "manual_confirmation",
    requires_manual_confirmation: true,
    is_sensitive_price: true,
    is_public_price: false,
    source_type: "available_offer",
    source_url: "",
    last_checked: "",
    status: "active",
    recommendable: true,
    exclude_from_recommendations: false,
    calculation_price_available: true,
    use_for_savings_calc: true,
    display_price_requires_confirmation: true,
    requires_pad: true,
    recommended_for: "Users who need large Canada data with unlimited Canada talk and text",
    caution: "Requires manual confirmation. Intended with pre-authorized debit setup."
  },
  {
    offer_id: "bell_mobile_175gb_internal_45",
    provider: "Bell",
    service_type: "mobile",
    plan_name: "Bell 175GB Canada-US-Mexico",
    speed_down: null,
    speed_up: null,
    mobile_data: "175GB",
    province: "Canada",
    region: "Canada",
    official_regular_price: null,
    official_promo_price: null,
    bill_saver_target_price: 45,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "manual_confirmation",
    credit_check_required: true,
    supports_phone_financing: "unknown",
    support_level: "manual_confirmation",
    requires_manual_confirmation: true,
    is_sensitive_price: true,
    is_public_price: false,
    source_type: "available_offer",
    source_url: "",
    last_checked: "",
    status: "active",
    recommendable: true,
    exclude_from_recommendations: false,
    calculation_price_available: true,
    use_for_savings_calc: true,
    display_price_requires_confirmation: true,
    requires_pad: true,
    recommended_for: "Heavy data users who need Canada, USA and Mexico usage",
    caution: "Requires manual confirmation. Intended with pre-authorized debit setup."
  },
  {
    offer_id: "bell_mobile_winback_manual",
    provider: "Bell",
    service_type: "mobile",
    plan_name: "Bell Available Offer - Manual Confirmation",
    speed_down: null,
    speed_up: null,
    mobile_data: null,
    province: "Canada",
    region: "Canada",
    official_regular_price: null,
    official_promo_price: null,
    bill_saver_target_price: null,
    is_bundle: false,
    bundle_discount: null,
    billing_type: "winback",
    credit_check_required: "unknown",
    supports_phone_financing: "unknown",
    support_level: "manual_confirmation",
    requires_manual_confirmation: true,
    is_sensitive_price: true,
    is_public_price: false,
    source_type: "internal_channel",
    source_url: "",
    last_checked: "",
    status: "inactive",
    recommendable: false,
    exclude_from_recommendations: true,
    use_for_savings_calc: false,
    recommended_for: "Users who want to manually compare currently available Bell mobile options",
    caution: "Available offers are not guaranteed and require manual eligibility confirmation."
  },
  {
    offer_id: "koodo_internet_mobile_bundle",
    provider: "Koodo",
    service_type: "both",
    plan_name: "Koodo Internet + Mobile",
    speed_down: null,
    speed_up: null,
    mobile_data: null,
    province: "Canada",
    region: "Canada",
    official_regular_price: 125,
    official_promo_price: 110,
    bill_saver_target_price: 95,
    is_bundle: true,
    bundle_discount: 10,
    billing_type: "postpaid",
    credit_check_required: true,
    supports_phone_financing: true,
    support_level: "standard",
    requires_manual_confirmation: true,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "estimated_public",
    source_url: "https://www.koodomobile.com/en/shop/subscriptions/internet",
    last_checked: "",
    status: "needs_verification",
    recommended_for: "Users who may combine Koodo mobile and home internet",
    caution: "Bundle discount and eligibility require confirmation."
  },
  {
    offer_id: "bell_internet_mobile_bundle",
    provider: "Bell Aliant",
    service_type: "both",
    plan_name: "Bell Aliant Internet + Better TV",
    speed_down: "1.5G",
    speed_up: "940M",
    mobile_data: null,
    province: "PEI",
    region: "PEI",
    official_regular_price: null,
    official_promo_price: null,
    bill_saver_target_price: 90,
    is_bundle: true,
    bundle_discount: null,
    billing_type: "manual_confirmation",
    credit_check_required: true,
    supports_phone_financing: false,
    support_level: "manual_confirmation",
    requires_manual_confirmation: true,
    is_sensitive_price: true,
    is_public_price: false,
    source_type: "available_offer",
    source_url: "https://aliant.bell.ca/",
    last_checked: "",
    status: "active",
    recommendable: true,
    exclude_from_recommendations: false,
    calculation_price_available: true,
    use_for_savings_calc: true,
    display_price_requires_confirmation: true,
    requires_installation_check: true,
    bundle_services: ["internet", "tv"],
    tv_package: "Better TV",
    tv_highlights: ["TSN HD"],
    recommended_for: "Households comparing Bell Aliant internet and Better TV",
    caution: "Final price, address availability, eligibility, installation, taxes, equipment fees, channel lineup, and credit approval require manual confirmation."
  },
  {
    offer_id: "bell_internet_better_tv_home_phone_bundle",
    provider: "Bell Aliant",
    service_type: "both",
    plan_name: "Bell Aliant Internet + Better TV + Home Phone",
    speed_down: "1.5G",
    speed_up: "940M",
    mobile_data: null,
    province: "PEI",
    region: "PEI",
    official_regular_price: null,
    official_promo_price: null,
    bill_saver_target_price: 100.7,
    is_bundle: true,
    bundle_discount: null,
    billing_type: "manual_confirmation",
    credit_check_required: true,
    supports_phone_financing: false,
    support_level: "manual_confirmation",
    requires_manual_confirmation: true,
    is_sensitive_price: true,
    is_public_price: false,
    source_type: "available_offer",
    source_url: "https://aliant.bell.ca/",
    last_checked: "",
    status: "active",
    recommendable: true,
    exclude_from_recommendations: false,
    calculation_price_available: true,
    use_for_savings_calc: true,
    display_price_requires_confirmation: true,
    requires_installation_check: true,
    bundle_services: ["internet", "tv", "home_phone"],
    tv_package: "Better TV",
    tv_highlights: ["TSN HD"],
    recommended_for: "Households comparing Bell Aliant internet, Better TV, and home phone",
    caution: "Final price, address availability, eligibility, installation, taxes, equipment fees, channel lineup, home phone details, and credit approval require manual confirmation."
  },
  {
    offer_id: "eastlink_internet_mobile_bundle",
    provider: "Eastlink",
    service_type: "both",
    plan_name: "Eastlink Internet + Mobile",
    speed_down: null,
    speed_up: null,
    mobile_data: null,
    province: "PEI",
    region: "PEI",
    official_regular_price: 150,
    official_promo_price: 125,
    bill_saver_target_price: 110,
    is_bundle: true,
    bundle_discount: null,
    billing_type: "postpaid",
    credit_check_required: "unknown",
    supports_phone_financing: true,
    support_level: "standard",
    requires_manual_confirmation: true,
    is_sensitive_price: false,
    is_public_price: true,
    source_type: "estimated_public",
    source_url: "https://www.eastlink.ca/",
    last_checked: "",
    status: "needs_verification",
    recommended_for: "Existing Eastlink users comparing bundle options",
    caution: "Bundle pricing and availability require confirmation."
  }
];

const defaultOfferFields = {
  commission_estimate: 0,
  partner_status: "none",
  recommendation_weight: "standard",
  show_premium_cta: false,
  trial_or_guarantee: null,
  trial_note: "",
  installation_fee: null,
  activation_fee: null,
  self_install_available: null,
  technician_install_available: null
};

export const offerDatabase = baseOfferDatabase.map((offer) => {
  if (offer.offer_id.startsWith("purple_cow_")) {
    return {
      ...defaultOfferFields,
      ...offer,
      commission_estimate: 25,
      partner_status: "active_partner",
      recommendation_weight: "medium_high",
      show_premium_cta: true,
      installation_fee: 0,
      activation_fee: 0,
      trial_or_guarantee: "first_month_money_back"
    };
  }

  if (offer.offer_id === "koodo_internet_100" || offer.offer_id === "koodo_internet_300" || offer.offer_id === "koodo_internet_gigabit") {
    return {
      ...defaultOfferFields,
      ...offer,
      commission_estimate: 60,
      partner_status: "priority_partner",
      recommendation_weight: "high",
      show_premium_cta: true,
      activation_fee: 0,
      self_install_available: true,
      technician_install_available: "confirm_by_address",
      trial_or_guarantee: "30_day_free_trial",
      trial_note: "Installation method, refund terms, eligibility, and final pricing should be confirmed with Koodo's current terms."
    };
  }

  return {
    ...defaultOfferFields,
    ...offer
  };
});
